#!/bin/sh

# This script is not used for now
# Disable this service, so it only gets run on first boot
systemctl disable halium9-post-install.service

# Start phosh
[[ -e /usr/bin/phosh ]] && systemctl start phosh
